# list of random comments
random_stoll = [
    "Licht ist keine Grenzgeschwindigkeit, vorsicht. Skalarwellen und stehende Welle hat ein vielfaches mehr!",
    "Auf die Maßeinheiten der Kernphysik hab ich bewusst verzichtet, denn außer mir würde das kaum jemand begreifen!",
    "Das ist ein ganz einfacher Algorithmus!",
    "Primzahlen bis 1024 werden in der Computertechnik benutzt!",
    "Wurzelrechnung... lächerlich!",
    "Die Erde ist ein lebender Organismus!",
    "Es gibt einen energetischen Frühling!",
    "Wir haben Blei verwandelt in Gold und Silber, Platin!",
    "Ich bin auch ein Anhänger der Kataklysmen-Theorie!",
    "Es handelt sich demnach um einen deutlichen und jederzeit reproduzierbaren Beweis für Homöopathie!",
    "Die Zahl 12 - auch ne kosmische Zahl!",
    "Angewandte MaTHEMAtik!",
    "Quarz als Skalarwelleninterferometer!",
    "Auch ne kosmische Zahl!",
    "Aber Vorsicht bei der Numerologie!",
    "Merkt ihr die Korrelation? Nachdenken!",
    "Man muss das dazu auch mal philosophisch betrachten!",
    "Aber steigtert euch nicht zu tief hinein - ich denke da an die Zahl 23 und was es alles gibt!",
    "Es gibt auch nen Vier-dimensionalen Würfel!",
    "Vier-dimensionale Räume, gibt es!",
    "Skalarwellen knallen quer Kontinente und Ozeane!",
    "Die jetzige elektromagnetische Theorie, wie sie an Schulen und Universitäten vertreten wird, ist falsch!",
    "Mit Überlichtgeschwindigkeit, ich betone: ÜBERLICHTGESCHWINDIGKEIT!",
    "Das ist ausgestoßene, überschüssige Geschwindigkeit! Mehr ist das nicht Leute!",
    "Wer kennt die Maxwell'schen Gleichungen?",
    "Was sind die Pyramiden, wer weiß das? Schlüssel der Energie!",
    "Magnetohydrodynamik!",
    "Wir leben in einer Welt von Schwingungen, sprich Frequenzen, und damit korrelierender Wirbelmechanismen!",
    "Alles ist nur Bewegung oder Geschwindigkeit oder Schwingung!",
    "Das ist eine Aufkraft!",
    "Weisste was die Primzahlen bedeuten? Einen Torus - raum-zeitlich gesehen!",
    "Alles nur störende Mikrowellen!",
    "Das A&O in der freien - in der Physik!",
    "Gemeint ist das organische Germanium 32!",
    "Unsere Energiegruppe ist in der Lage das künstlich herzustellen!",
    "Mikrowelle, Skalarwelle!",
    "Physik, Mathematik, Philosophie!",
    "Wir Physiker sprechen vom sogenannten Dirac-Meer!",
    "Die muss man anzapfen entsprechend einem Implusions-Strudel!",
    "Sie ist ein Perpetuum Mobile!",
    "Das heißt eine logarithmische Spirale raum-zeitlich betrachtet nach Innen!",
    "Das ist die menschliche Zelle im Schnitt!",
    "Das nennt man KALTE FUSION!",
    "Es gibt nur Expansionsstrudel und Implosionsstrudel!",
    "Es gibt keine feste Materie - das ist ein Trugschluss!",
    "Mann muss immer den Ursprung erkennen - den Algorithmus, meine Damen, meine Herren!",
    "Die Natur bracht Wirbel!",
    "Formeln sind viel besser zu Handhaben, ist wie ein Krimi!",
    "Mathematik ist die Sprache des Universums, der Intelligenz und erspart mir 1000 Seiten zu lesen!",
    "Man steckt erst richtig drin im Wissen, wenn man auch einer Klofrau das Raum/Zeit-Gefüge erklären kann!",
    "Das ist eine stehende Welle, die ist sofort da!",
    "Der Mensch ist eine energetische Matrix!",
    "Physik ist Magie durch wollen!",
    "Meine Name ist Stoll, ich bin promovierter Naturwissenschaftler!",
    "Ich befasse mich mit freier Energie!",
    "Implosionstechnologie!",
    "Biologie ist Physik!",
    "Mit Kraft!",
    "Das ist kein Science Fiction!",
    "So einfach ist das, wenn man um die neue Physik weiß!",
    "Ich kann auch radioaktive Strahlung neutralisieren!",
    "So lebt man ruhiger und energetischer!",
    "Es gibt nur energetische Felder!",
]