# dictionaries of questions with 4 answers each (the correct one is always the first)
kt_questions = {
    "Ist der Entdecker des Neutrinos Fan eines Hamburger Fußball-Zweitligisten, dann unterstützt der ...": ("Wolfgang Pauli", "Enrico Fermi", "Richard Feynman", "Peter Higgs"),
    "Nukleone und Nuklide: Was zeichnet ein Isotop aus?": ("gleiche Protonenzahl Z", "gleiche Massezahl A", "gleiche Neutronenzahl N", "gleicher Bizepsumfang"),
    "Nukleone und Nuklide: Was zeichnet ein Isoton aus?": ("gleiche Neutronenzahl N", "gleiche Protonenzahl Z", "gleiche Massezahl A", "gleicher Bizepsumfang"),
    "Nukleone und Nuklide: Was zeichnet ein Isobar aus?": ("gleiche Massezahl A", "gleiche Protonenzahl Z", "gleiche Neutronenzahl N", "gleicher Bizepsumfang"),
    "Tröpfchenmodell: Bei welcher Energie hat die Bindungsenergie pro Nukleon laut Bethe-Weizsäcker-Massenformel ihr Maximum?": ("8,7 MeV", "8,7 GeV", "93 GeV", "7,8 GeV"),
    "Tröpfchenmodell: Bei welcher atomaren Massezahl A hat die Bindungsenergie pro Nukleon laut Bethe-Weizsäcker-Massenformel ihr Maximum?": ("A = 60", "A = 40", "A = 80", "A = 20"),
    "Tröpfchenmodell: Wie lautet der Beitrag des Volumentermsterms E_V zur Bindungsenergie?": ("E_V = a_V * A", "E_V = -a_V * A", "E_V = a_V * Z^2 * A^(-1/3)", "E_V = a_V * Z^2 * A^(-1/3)"),
    "Tröpfchenmodell: Wie lautet der Beitrag des Oberflächenterms E_S zur Bindungsenergie?": ("E_S = -a_S * A^(2/3)", "E_S = -a_S * A^(-2/3)", "E_S = -a_S * A^(1/3)", "E_S = -a_S * A^(-1/3)"),
    "Tröpfchenmodell: Wie lautet der Beitrag des Coulombterms E_C zur Bindungsenergie?": ("E_C = -a_C * Z^2 * A^(-1/3)", "E_C = -a_C * Z^2 * A^(-2/3)", "E_C = -a_C * Z^2 * A^(1/3)", "E_C = -a_C * Z^2 * A^(2/3)"),
    "Tröpfchenmodell: Wie lautet der Beitrag des Symmetrieterms E_sym zur Bindungsenergie?": ("E_S = -a_S * (N-Z)^2 / A", "E_S = -a_S * (N-Z)^2 * A^(-1/2)", "E_S = -a_S * (A-Z)^2 * A^(-1/2)", "E_S = -a_S * (A-N)^2 / A^2"),
    "Tröpfchenmodell: Wie lautet der Beitrag des Paarungsterms E_P zur Bindungsenergie mit delta = (+/-) 1?": ("E_P = a_P * delta * A^(-1/2)", "E_P = a_P * delta * A^(1/2)", "E_P = a_P * delta * A", "E_P = a_P * delta / A"),
    "Tröpfchenmodell: Was tritt für Atome mit niedrigerer atomaren Massezahl A als der des Maximums der Bindungsenergie bevorzugt auf?": ("Fusionen", "beta- Zerfälle", "beta+ Zerfälle", "Zerfälle"),
    "Tröpfchenmodell: Was tritt für Atome mit größerer atomaren Massezahl A als der des Maximums der Bindungsenergie bevorzugt auf?": ("Zerfälle", "Fusionen", "beta- Zerfälle", "beta+ Zerfälle"),
    "Tröpfchenmodell: Was tritt für Isobare mit niedrigerer Ladungszahl als dem leichtesten Isobar bevorzugt auf?": ("beta- Zerfälle", "beta+ Zerfälle", "Fusionen", "Zerfälle"),
    "Tröpfchenmodell: Was tritt für Isobare mit größerer Ladungszahl als dem leichtesten Isobar bevorzugt auf?": ("beta+ Zerfälle", "beta- Zerfälle", "Fusionen", "Zerfälle"),
    "Tröpfchenmodell: Bei welcher Ladungszahl Z existiert für Massezahl A = 100 das leichteste und damit stabilste Isobar für gg oder uu Kerne?": ("Z = 42 und Z = 44", "Z = 44 (Ruthenium)", "Isobare sind immer gleich schwer", "für gerade Massezahlen A existiert ein schwerstes Isobar"),
    "Tröpfchenmodell: Bei welcher Ladungszahl Z existiert für Massezahl A = 101 das leichteste und damit stabilste Isobar für gu oder ug Kerne?": ("Z = 44 (Ruthenium)", "Z = 42 und Z = 44", "Isobare sind immer gleich schwer", "für ungerade Massezahlen A existiert ein schwerstes Isobar"),
    "Tröpfchenmodell: Welche Masse besitzt ein typisches (A = 100) leichtestes Isobar laut Bethe-Weizsäcker-Massenformel?": ("93 GeV", "8,7 MeV", "8,7 GeV", "7.8 GeV"),
    "Radioaktive Zerfälle: Was gilt für den Zusammenhang zwischen Halbwertszeit t_(1/2) und Zerfallskonstante lambda?": ("t_(1/2) = ln(2) / lambda", "t_(1/2) = -ln(2) / lambda", "t_(1/2) = lambda / ln(2)", "t_(1/2) = -lambda / ln(2)"),
    "Radioaktive Zerfälle: Was gilt für den Zusammenhang zwischen Halbwertszeit t_(1/2) und mittlerer Lebensdauer <t>?": ("t_(1/2) = ln(2) * <t>", "t_(1/2) = ln(2) / <t>", "t_(1/2) = 1 / <t>", "t_(1/2) = -ln(2) / <t>"),
    "Radioaktive Zerfälle: Was gilt für die mittlerer Lebensdauer <t> mit Zerfallskonstante lambda und Halbwertszeit t_(1/2)?": ("<t> = 1 / lambda", "<t> = t_(1/2)", "<t> = t_(1/2) / lambda", "<t> = t_(1/2) * ln(2)"),
    "Radioaktive Zerfälle: Was gilt für die mittlerer Lebensdauer <t> mit Zerfallskonstante lambda und Halbwertszeit t_(1/2)?": ("<t> = t_(1/2) / ln(2)", "<t> = t_(1/2) / lambda", "<t> = t_(1/2) * ln(2)", "<t> = t_(1/2)"),
    "Multimoden-Zerfälle: Was gilt für die Gesamt-Zerfallskonstante lambda_tot für die Zerfallskonstanten lambda_A und lambda_B?": ("lambda_tot = lambda_A + lambda_B", "lambda_tot = 1 / (lambda_A + lambda_B)", "lambda_tot = lambda_A * lambda_B", "lambda_tot = lambda_A / lambda_B"),
    "Multimoden-Zerfälle: Welcher Zusammenhang gilt zwischen Zerfallskonstante lambda_A und Zerfallswahrscheinlichkeint P_A mit Gesamt-Zerfallskonstante lambda_tot?": ("lambda_A = P_A * lambda_tot", "lambda_A = P_A / lambda_tot", "lambda_A = lambda_tot / P_A", "lambda_A = P_A"),
    "Mehrstufige radioaktive Zerfälle: Wie lautet die Differentialgleichung für N_B für den 2-stufigen Zerfall 'A -lambda_1 -> B - lambda_2 -> C'?": ("dN_B/dt = lambda_1*N_A - lambda_2*N_B", "dN_B/dt = lambda_1*N_B - lambda_2*N_A", "dN_B/dt = lambda_1*N_B - lambda_2*N_C", "dN_B/dt = lambda_1*N_C - lambda_2*N_B"),
    "Kernspaltung und Kettenreaktionen: Welches Uran wird in Kernreaktoren benötigt?": ("U-235", "U-238", "U-232", "jedes Uranisotop ist leicht spaltbar und kann verwendet werden"),
    "Kernspaltung und Kettenreaktionen: Wie groß ist der Anteil des Uranisotops U-238 in natürlichem Uran?": ("99,3 %", "93 %", "97 %", "3 %"),
    "Kernspaltung und Kettenreaktionen: Wie groß ist typischerweise der Anteil des Uranisotops U-235 in dem angereichertem Uran in Kernreaktoren?": ("3 %", "15 %", "50 %", "97 %"),
    "Kernspaltung und Kettenreaktionen: Was macht leichtes Wasser in einem Reaktor?": ("es nimmt Neutronen auf und unterbindet damit die Kernspaltung", "es dient als Moderator und bremst Neutronen ab, eine Kettenreaktion findet statt", "es reagiert mit Uran zu Uranhydroxid", "es ist ein selbst-regulierender Moderator mit Multiplikationsfaktor k = 1, keine Steuerstäbe werden benötigt"),
    "Relativitätstheorie: Was gilt für die Länge des Differenzvierervektors dl^2 wenn der Abstand zweier Ereignisse x_1 und x_2 als 'zeitartig' bezeichnet wird?": ("dl^2 > 0", "dl^2 < 0", "dl^2 = 0", "dl^2 ist immer die Masse"),
    "Relativitätstheorie: Was gilt für die Länge des Differenzvierervektors dl^2, wenn der Abstand zweier Ereignisse x_1 und x_2 als 'lichtartig' bezeichnet wird?": ("dl^2 = 0", "dl^2 < 0", "dl^2 > 0", "s^2 ist immer die Masse"),
    "Relativitätstheorie: Wie wird der Abstand zweier Ereignisse x_1 und x_2 bezeichnet wenn für die Länge des Differenzvektors dl^2 < 0 gilt?": ("raumartig", "zeitartig", "lichtartig", "die Länge eines Differenzvektors ist immer dl^2 = 0"),
    "Relativitätstheorie: Wie lautet der relativistische Satz des Pythagoras?": ("p^2 = E^2 - Vec(p)^2", "p^2 = E^2 + Vec(p)^2", "p^2 = Vec(p)^2 - E^2", "-p^2 = E^2 + Vec(p)^2"),
    "Relativitätstheorie: Wie groß ist der Betrag eines Viererimpulses p^2?": ("es ist immer die Masse m^2", "immer 0", "es ist immer die Energie E^2", "es ist das Betragsquadrat des Dreierimpulses Vec(p)^2"),
    "Mandelstam-Variablen: Was gilt für die Mandelstamvariable s?": ("s = (p_1 + p_2)^2 = (p_3 + p_4)^2", "s^2 = (p_1 + p_2)^2 = (p_3 + p_4)^2", "s = (p_1 - p_2)^2 = (p_3 - p_4)^2", "s^2 = (p_1 - p_2)^2 = (p_3 - p_4)^2"),
    "Mandelstam-Variablen: Was gilt für die Mandelstamvariable t?": ("t = (p_1 - p_3)^2 = (p_2 - p_4)^2", "t^2 = (p_1 - p_3)^2 = (p_2 - p_4)^2", "t = (p_1 - p_2)^2 = (p_3 - p_4)^2", "t^2 = (p_1 - p_2)^2 = (p_3 - p_4)^2"),
    "Mandelstam-Variablen: Was trifft auf einen Prozess im t-Kanal zu?": ("raumartig", "zeitartig", "lichtartig", "es ist nicht klar definiert"),
    "Mandelstam-Variablen: Was gilt für das Quadrat des Viererimpulses q^2 des vermittelnden Photons eines Prozesses im u-Kanal mit Mandelstam-Variable u zu?": ("q^2 = u", "q^2 = u^2", "q^2 = sqrt(u)", "q = u^2"),
    "Mandelstam-Variablen: Was ist gleich der Summe der drei Mandelstamvariablen s + t + u?": ("s + t + u = m_1^2 + m_2^2 + m_3^2 + m_4^2", "s + t + u = 2*m_1^2 + 2*m_2^2", "s + t + u = 4*m_1^2 - 4*m_3^2", "s + t + u = 4*m_1^2"), 
    "Mandelstam-Variablen: Was gilt in der Hochenergie-Näherung?": ("E^2 = |Vec(p)|^2", "E^2 = m^2", "m^2 = |Vec(p)|^2", "m^2 = |Vec(p)|^2 - E^2"),
    "Fixed-Target Experiment: Was trifft auf den totalen Energie-Impuls-Vierervektor im Fixed-Target Experiment zu?": ("variant und erhalten", "invariant und erhalten", "variant und nicht erhalten", "invariant und nicht erhalten"),
    "Fixed-Target Experiment: Was trifft auf die Vektorsumme der Geschwindigkeiten im Fixed-Target Experiment zu?": ("variant und nicht erhalten", "invariant und erhalten", "variant und erhalten", "invariant und nicht erhalten"),
    "Fixed-Target Experiment: Was trifft auf die Masse des Gesamtsystems im Fixed-Target Experiment zu?": ("invariant und erhalten", "variant und erhalten", "variant und nicht erhalten", "invariant und nicht erhalten"),
    "Fixed-Target Experiment: Was trifft auf die Baryonenzahl im Fixed-Target Experiment zu?": ("invariant und erhalten", "variant und erhalten", "variant und nicht erhalten", "invariant und nicht erhalten"),
    "Fixed-Target Experiment: Was trifft auf die Summe der Ruhemassen im Fixed-Target Experiment zu?": ("invariant und nicht erhalten", "invariant und erhalten", "variant und nicht erhalten", "variant und erhalten"),
}


fk_questions = {
    "Ein Festkörper ist ...": ("fest", "weich", "flüssig", "gasförmig"),
}